- name: install nginx
  hosts: web
  become: yes
  tasks:
  - name: print the stats
    ansible.builtin.debug:
      msg: "{{ ansible_files }}"

  - name: install nginx if redhat
    ansible.builtin.dnf:
    name: nginx
    state: present
  when: ansible_os_family == "RedHat"

  - name: install nginx if debian
    nsible.builtin.apt:
      name: nginx
      state: present
  when: ansible_os_family == "debian"

  