# - name: create ec2 and r53 records
#   hosts: local
#   connection: local
#   vars:
#     subnet_id: subnet-0989cb013695510f4
#     sg_id: "sg-0e14df2a29d5415f7"
#     ami_id: "ami-09c813fb71547fc4f"
#     instances:
#     - mysql
#     - backend
#     - frontend

#   tasks:
#   - name: create ec2 instance
#     amazon.aws.ec2_instance:
#       name: "{{ item }}"
#       vpc_subnet_id: "{{ subnet_id }}"
#       instance_type: "t3.micro"
#       securiy_group: "{{ sg_id }}"
#       image_id: "{{ ami_id }}"
#     loop: "{{ instances }}"
#     register: ec2_instances

#   - name: print the output
#     ansible.builtin.debug:
#       msg: "{{ ec2_instances }}"


- name: create ec2 and r53 records
  hosts: local
  connection: local
  # assignment
  # move this to vars_files
  vars:
    subnet_id: subnet-0989cb013695510f4 # replace with your subnet id
    sg_id: "sg-0e14df2a29d5415f7"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
    zone: daws81s.online
  tasks:
  - name: ansible to install boto3 and botocore
    ansible.builtin.pip:
      name:
      - boto3
      - botocore
      executable: pip3.9
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"









